---

- hosts: web_server
  become: true
  tasks:
    - name: Install apache & php support
      package:
        name:
          - apache2
          - libapache2-mod-php
        state: present
        update_cache: true