---

- hosts: web_server
  become: true
  tasks:
    - name: Remove apache and libapache2-mod-php packages
      package:
        name:
          - apache2
          - libapache2-mod-php
        state: absent
        update_cache: true